-- Run this in phpMyAdmin SQL tab
-- Adds missing deletedAt column to all paranoid tables

ALTER TABLE `Branches` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Categories` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Comments` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Contacts` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Contracts` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Countries` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `EADocuments` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Expenses` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `LeadComments` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `LeadDocuments` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `LeadReplies` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Replies` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `Tasks` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `taskActivities` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
ALTER TABLE `taskComments` ADD COLUMN IF NOT EXISTS `deletedAt` DATETIME NULL DEFAULT NULL;
